apiVersion: v1
kind: Secret
metadata:
  name: es-secret
type: Opaque
data:
  username: mcwenfkqfwef
  password: UYiuagfjk2hj

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elasticsearch-logging-v1
  namespace: kube-system
  labels:
    k8s-app: elasticsearch-logging
    version: v5.6.2
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  replicas: {{ .Values.esReplicas }}
  template:
    metadata:
      labels:
        k8s-app: elasticsearch-logging
        version: v5.6.2
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - image: elasticsearch:5.6.3
        imagePullPolicy: Always
        name: elasticsearch-logging
        resources:
          # need more cpu upon initialization, therefore burstable class
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        ports:
        - containerPort: 9200
          name: db
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: es-persistent-storage
          mountPath: /data
        env:
        - name: "CLUSTER_NAME"
          value: "myesdb"
        - name: "NODE_NAME"
          value: "es"
        - name: "NODE_MASTER"
          value: "true"
        - name: "NODE_DATA"
          value: "true"
        - name: "MINIMUM_MASTER_NODES"
          value: "1"
        - name: "NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: "ES_JAVA_OPTS"
          value: "-Xms4g -Xmx4g"
        - name: "NETWORK_HOST"
          value: "0.0.0.0"
        - name: "HTTP_ENABLE"
          value: "true"
        - name: "HTTP_CORS_ENABLE"
          value: "true"
        - name: "HTTP_CORS_ALLOW_ORIGIN"
          value: "*"
        - name: "HTTP_PORT"
          value: "9200"
        - name: "HTTP_COMPRESSION"
          value: "true"
        - name: "NODE_INGEST"
          value: "false"
        - name: "TRANSPORT_PORT"
          value: "9300"
        - name: "ELASTICSEARCH_HOST"
          value: "elasticsearch-logging"
        - name: "ELASTICSEARCH_PORT"
          value: "9200"
        - name: "DELETE_OLDER_THAN_DAY"
          valueFrom:
            configMapKeyRef:
              name: environment
              key: RETAIN_LOGS_DAYS
        - name: "NUMBER_OF_MASTERS"
          value: "1"
        - name: "MAX_LOCAL_STORAGE_NODES"
          value: "1"
        - name: "XPACK_MONITORING_ENABLED"
          value: "false"
        - name: "XPACK_SECURITY_ENABLED"
          value: "false"
        - name: "XPACK_SECURITY_AUDIT_ENABLED"
          value: "false"
        - name: "XPACK_GRAPH_ENABLED"
          value: "false"
        - name: "XPACK_ML_ENABLED"
          value: "false"
        - name: "ES_USERNAME"
          valueFrom:
            configMapKeyRef:
              name: elasticsearch-config
              key: ES_USER
        - name: "ES_PASSWORD"
          valueFrom:
            configMapKeyRef:
              name: elasticsearch-config
              key: ES_PASSWORD
      initContainers:
      - image: alpine:3.6
        command: ["/sbin/sysctl", "-w", "vm.max_map_count=262144"]
        name: elasticsearch-logging-init
        securityContext:
          privileged: true
      volumes:
        - name: es-persistent-storage
          awsElasticBlockStore:
            volumeID: {{ required "Please provide dataVolumeEBS" .Values.dataVolumeEBS }}
            fsType: ext4
        - name: es-config-volume
          configMap:
            name: elasticsearch-config

---

apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-logging
  namespace: kube-system
  labels:
    k8s-app: elasticsearch-logging
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "Elasticsearch"
spec:
  ports:
  - port: 9200
    protocol: TCP
    targetPort: db
  selector:
    k8s-app: elasticsearch-logging
