apiVersion: v1
kind: Service
metadata:
  name: postgres3
  labels:
    app: postgres3
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: postgres3
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app: postgres3 # has to match .spec.template.metadata.labels
  serviceName: "postgres3"
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        app: postgres3 # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: postgres3
        image: gcr.io/extreme-signer-231907/postgres:9.6
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: superpostgres
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgresdata
  volumeClaimTemplates:
  - metadata:
      name: postgresdata
      annotations:
        volume.beta.kubernetes.io/storage-class: "slow"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
